# Generated by Django 4.0.2 on 2022-04-14 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('books', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
                ('title', models.CharField(max_length=180)),
                ('content', models.CharField(max_length=900)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='users.customer')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Book', to='books.book')),
            ],
        ),
    ]
