# Generated by Django 4.0.2 on 2022-04-04 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
        ('bookRating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='userz',
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(default='Commentor', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='book',
            field=models.ForeignKey(default='Comment', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
