# Generated by Django 4.0.2 on 2022-04-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.PositiveSmallIntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')]),
        ),
    ]
