# Generated by Django 4.0.2 on 2022-04-05 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
        ('bookRating', '0002_remove_comments_userz_comments_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(max_length=10)),
                ('book', models.ForeignKey(default='Title', on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('user', models.ForeignKey(default='first_name', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
