# Generated by Django 4.0.2 on 2022-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookRating', '0004_alter_comment_options_alter_comment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')]),
        ),
    ]
