# Generated by Django 4.0.2 on 2022-04-05 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0001_initial'),
        ('bookRating', '0004_alter_comment_book_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='book',
            field=models.ForeignKey(default='Title', on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default='first_name', on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
