# Generated by Django 3.2.12 on 2022-04-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Bio', models.CharField(max_length=10000)),
                ('Publisher', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Book_Description', models.CharField(max_length=10000)),
                ('Genre', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Year_Published', models.IntegerField()),
                ('Copies_Sold', models.IntegerField()),
                ('ISBN', models.IntegerField()),
            ],
        ),
    ]
