# Generated by Django 3.2.12 on 2022-04-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Author_ID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='Copies_Sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='Year_Published',
            field=models.IntegerField(),
        ),
    ]
