# Generated by Django 3.2.12 on 2022-04-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220401_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Author_ID',
        ),
    ]
