# Generated by Django 3.2.12 on 2022-03-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220329_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Author_ID',
            field=models.IntegerField(max_length=200, null=b'I00\n'),
            preserve_default=b'I00\n',
        ),
        migrations.AddField(
            model_name='book',
            name='Author_ID',
            field=models.IntegerField(max_length=200, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='book',
            name='Copies_Sold',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='Year_Published',
            field=models.IntegerField(max_length=200),
        ),
    ]
