# Generated by Django 4.0.2 on 2022-03-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creditCard_number', models.CharField(max_length=200)),
                ('creditCard_expiration', models.CharField(max_length=4)),
                ('creditCard_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='creditCard_number',
        ),
    ]
