# Generated by Django 4.0.2 on 2022-03-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_creditcard_remove_users_creditcard_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('creditCard_number', models.CharField(max_length=200)),
                ('creditCard_expiration', models.CharField(max_length=4)),
                ('creditCard_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='CreditCard',
        ),
    ]
