# Generated by Django 4.0.2 on 2022-04-01 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220329_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='cc_number',
            new_name='cardNumber',
        ),
    ]
