# Generated by Django 4.0.2 on 2022-04-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_number_users_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='number',
        ),
    ]
