# Generated by Django 4.0.2 on 2022-04-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_delete_users'),
        ('users', '0012_customer_address'),
    ]

    operations = [
    ]
