# Generated by Django 4.0.2 on 2022-04-01 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_cc_number_users_cardnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='cardNumber',
            new_name='Number',
        ),
    ]
