# Generated by Django 4.0.2 on 2022-04-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Author', models.CharField(max_length=200)),
                ('Price', models.FloatField()),
                ('Book_Description', models.CharField(max_length=10000)),
                ('Genre', models.CharField(max_length=200)),
                ('Publisher', models.CharField(max_length=200)),
                ('Year_Published', models.IntegerField()),
                ('Copies_Sold', models.IntegerField()),
                ('score', models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***'), (4, '****'), (5, '*****')])),
                ('ISBN', models.IntegerField()),
            ],
        ),
    ]
