# Generated by Django 4.0.2 on 2022-04-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_cart_delete_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user_id',
        ),
    ]
