# Generated by Django 4.0.2 on 2022-04-14 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '__first__'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistenitity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist', models.CharField(max_length=200)),
                ('wishlistbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='books.book')),
                ('wishlistuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.customer')),
            ],
        ),
    ]
